#!/usr/bin/env bash
#
# scripts/configure-prod.sh — production hardening for a single-server ExecRelay.
#
# Prereq: scripts/install.sh has been run successfully and the stack is up.
#
# What this does:
#   1. Installs Caddy via Cloudsmith's official Ubuntu repo.
#   2. Writes /etc/caddy/Caddyfile from infra/caddy/Caddyfile.template,
#      substituting your DOMAIN and an admin bcrypt hash for Grafana.
#   3. Reloads caddy so it requests Let's Encrypt certs for {{DOMAIN}},
#      api.{{DOMAIN}}, hook.{{DOMAIN}}, admin.{{DOMAIN}}. (You must already
#      have DNS A records pointing at this server.)
#   4. Configures UFW to allow ONLY 22/tcp (SSH), 80/tcp, 443/tcp.
#   5. Installs and enables the execrelay.service systemd unit so the stack
#      restarts on boot.
#   6. Binds the still-exposed app ports (8081-8088, 3000, 3001, 9090, 9093,
#      5432, 4222, 6379) to 127.0.0.1 by editing docker-compose.override.yml —
#      they remain reachable from Caddy but not from the public internet.
#
# Usage (from repo root):
#   sudo DOMAIN=execrelay.example.com EMAIL=you@example.com \
#     bash scripts/configure-prod.sh
#
# Re-runs are safe: the script is idempotent.

# shellcheck source=lib.sh
source "$(dirname "$0")/lib.sh"

require_root
require_ubuntu

: "${DOMAIN:?DOMAIN env var is required (e.g. DOMAIN=execrelay.example.com)}"
: "${EMAIL:?EMAIL env var is required for Lets Encrypt (e.g. EMAIL=you@example.com)}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ---- 1. Caddy ------------------------------------------------------------------
install_caddy() {
  if command -v caddy >/dev/null 2>&1; then
    ok "caddy already installed ($(caddy version | head -1))"
    return
  fi
  log "installing Caddy from cloudsmith.io/caddy"
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg --yes
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy
  ok "Caddy installed"
}

# ---- 2. Caddyfile --------------------------------------------------------------
write_caddyfile() {
  log "writing /etc/caddy/Caddyfile for $DOMAIN"
  local template="$REPO_ROOT/infra/caddy/Caddyfile.template"
  if [ ! -f "$template" ]; then die "$template missing"; fi

  # Generate (or reuse) a bcrypt hash for Grafana basic-auth at admin.$DOMAIN.
  local pw_file=/etc/caddy/admin_password.txt
  local bcrypt_file=/etc/caddy/admin_bcrypt.txt
  if [ ! -s "$bcrypt_file" ]; then
    mkdir -p /etc/caddy
    local pw
    pw=$(gen_secret 24)
    printf '%s\n' "$pw" > "$pw_file"
    chmod 600 "$pw_file"
    caddy hash-password --plaintext "$pw" > "$bcrypt_file"
    chmod 600 "$bcrypt_file"
    warn "Grafana admin password for admin.$DOMAIN: $(cat "$pw_file")"
    warn "  (also saved to $pw_file, mode 0600; delete it after the password is stored somewhere safe)"
  fi
  local bcrypt
  bcrypt=$(cat "$bcrypt_file")

  # Inline sed to substitute placeholders — bcrypt contains '$' so use | as
  # delimiter and feed via a temp file to keep quoting sane.
  sed -e "s|{{DOMAIN}}|$DOMAIN|g" \
      -e "s|{{ADMIN_BCRYPT}}|$bcrypt|g" \
      "$template" > /etc/caddy/Caddyfile

  # Configure Caddy's Let's Encrypt account email globally.
  if ! grep -q "email $EMAIL" /etc/caddy/Caddyfile; then
    # Insert a global options block at the top.
    sed -i.bak "1i {\n\temail $EMAIL\n}\n" /etc/caddy/Caddyfile && rm -f /etc/caddy/Caddyfile.bak
  fi

  caddy validate --config /etc/caddy/Caddyfile || die "Caddyfile failed validation"
  systemctl reload caddy
  systemctl enable --now caddy
  ok "Caddy reloaded with new Caddyfile"
}

# ---- 3. Bind app ports to localhost only ---------------------------------------
write_compose_override() {
  log "writing docker-compose.override.yml to bind exposed ports to 127.0.0.1"
  cat > "$REPO_ROOT/docker-compose.override.yml" <<'OVERRIDE_EOF'
# Generated by scripts/configure-prod.sh — binds every host-exposed port to
# 127.0.0.1 so only Caddy (running on the host network) can reach them. Public
# traffic enters via 80/443 → Caddy → these loopback addresses.
#
# Re-running configure-prod.sh overwrites this file. Edit it manually only if
# you know what you're doing.

services:
  postgres:    { ports: ["127.0.0.1:5432:5432"] }
  nats:        { ports: ["127.0.0.1:4222:4222", "127.0.0.1:8222:8222"] }
  redis:       { ports: ["127.0.0.1:6379:6379"] }
  minio:       { ports: ["127.0.0.1:9000:9000", "127.0.0.1:9001:9001"] }
  prometheus:  { ports: ["127.0.0.1:9090:9090"] }
  alertmanager:{ ports: ["127.0.0.1:9093:9093"] }
  grafana:     { ports: ["127.0.0.1:3000:3000"] }
  tempo:       { ports: ["127.0.0.1:3200:3200", "127.0.0.1:4317:4317", "127.0.0.1:4318:4318"] }
  ingress:     { ports: ["127.0.0.1:8081:8080"] }
  bridge:      { ports: ["127.0.0.1:8082:8080"] }
  dxtrade:     { ports: ["127.0.0.1:8083:8080"] }
  persist:     { ports: ["127.0.0.1:8084:8080"] }
  portal-api:  { ports: ["127.0.0.1:8085:8080"] }
  tasks:       { ports: ["127.0.0.1:8086:8080"] }
  analytics:   { ports: ["127.0.0.1:8087:8080"] }
  reports:     { ports: ["127.0.0.1:8088:8080"] }
  portal-web:  { ports: ["127.0.0.1:3001:3000"] }
OVERRIDE_EOF
  ok "wrote docker-compose.override.yml"
}

# ---- 4. Firewall ---------------------------------------------------------------
configure_ufw() {
  log "configuring UFW (allow 22, 80, 443; deny everything else inbound)"
  apt-get install -y -qq ufw
  ufw --force reset >/dev/null
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow 22/tcp
  ufw allow 80/tcp
  ufw allow 443/tcp
  ufw --force enable
  ok "UFW active: $(ufw status | head -1)"
}

# ---- 5. systemd unit -----------------------------------------------------------
install_systemd_unit() {
  log "installing /etc/systemd/system/execrelay.service (auto-start on boot)"
  sed "s|{{REPO_ROOT}}|$REPO_ROOT|g" "$REPO_ROOT/infra/systemd/execrelay.service" \
    > /etc/systemd/system/execrelay.service
  systemctl daemon-reload
  systemctl enable execrelay.service
  ok "execrelay.service enabled (will start on next boot; already-running stack untouched)"
}

# ---- 6. Restart stack with new port bindings -----------------------------------
restart_stack() {
  log "restarting stack so the new port bindings take effect"
  ( cd "$REPO_ROOT" && docker compose --profile apps up -d --force-recreate )
  ok "stack restarted with loopback-only port bindings"
}

# ---- main ----------------------------------------------------------------------
log "configuring production reverse proxy + TLS for $DOMAIN"
install_caddy
write_caddyfile
write_compose_override
configure_ufw
install_systemd_unit
restart_stack

cat <<DONE

  ✓ Production hardening complete.

    DNS — point these A records at this server's public IP:
      $DOMAIN
      api.$DOMAIN
      hook.$DOMAIN
      admin.$DOMAIN

    Caddy will request Let's Encrypt certificates on first request to each
    domain. Check status with:  journalctl -u caddy -f

    Verify the firewall:  ufw status verbose
    Verify systemd unit:  systemctl status execrelay
    Verify app stack:     docker compose --profile apps ps

    Grafana admin password (write this down NOW):
      $(cat /etc/caddy/admin_password.txt 2>/dev/null || echo "(see /etc/caddy/admin_password.txt)")
DONE
