apiVersion: v1
kind: Secret
metadata:
  name: {{ include "execrelay.fullname" . }}-secrets
  labels:
    {{- include "execrelay.labels" . | nindent 4 }}
type: Opaque
stringData:
  nats-url: {{ .Values.natsUrl | quote }}
  database-url: {{ .Values.databaseUrl | quote }}
  jwt-secret: {{ .Values.jwtSecret | quote }}
  licenses: {{ .Values.licenses | quote }}
  pagerduty-key: {{ .Values.pagerdutyKey | quote }}
  slack-webhook-url: {{ .Values.slackWebhookUrl | quote }}
