{{- if .Values.prometheus.enabled }}
{{- range $serviceName, $service := .Values.services }}
{{- if ne $serviceName "portal-web" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "execrelay.fullname" . }}-{{ $serviceName }}
  labels:
    {{- include "execrelay.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  selector:
    matchLabels:
      {{- include "execrelay.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $serviceName }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ $.Values.prometheus.interval | default "30s" }}
{{- end }}
{{- end }}
{{- end }}
